'use strict';
const KEY='miranLabDataV1', today=()=>new Date().toLocaleDateString('sv-SE'), nowText=()=>new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date());
const homeworkSeed=[['complete','夏休みの完成',0],['tests','たしかめのテスト（国語・算数）',0],['challenge','チャレンジ漢字・計算',0],['diary','夏の一行日記',0],['bookguide','読書感想文の書き方',0],['bookreport','読書感想文（原稿用紙3枚）',0],['science','理科の観察（iPadに写真）',0],['picture','夏休みの思い出絵日記',0],['recorder','音楽・リコーダーの練習',0],['tooth','はみがきカレンダー',0],['contest','国語・図工コンクール応募',1],['research','自由研究',1]].map(([id,title,o])=>({id,title,optional:!!o}));
const defaultData={points:0,missions:{},daily:{},explore:[],homework:{},diaryEntries:[],kanjiDays:{},mathDays:{},kukuDays:{},kukuWeak:{},mathWeak:{},streak:{last:'',count:0}};
let data=load(),installPrompt=null,kukuMode='table',mathMode='add',kukuQuestions=[],mathQuestion=null,kukuTimer=null,kukuSeconds=30,kukuScore=0;
function clone(x){return JSON.parse(JSON.stringify(x))} function load(){try{const o=JSON.parse(localStorage.getItem(KEY)||'{}');return {...clone(defaultData),...o,homework:o.homework||{},kukuWeak:o.kukuWeak||{},mathWeak:o.mathWeak||{}}}catch{return clone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()} function award(n){data.points=Math.max(0,(data.points||0)+n)} function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function badge(p){return p>=1000?'ミラン研究所長':p>=500?'博士':p>=250?'主任研究員':p>=100?'研究員':p>=30?'見習い研究員':'はじめの一歩'}
function markStudy(type){const d=today(); if(data.streak.last!==d){const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);const y=yesterday.toLocaleDateString('sv-SE');data.streak.count=data.streak.last===y?(data.streak.count||0)+1:1;data.streak.last=d} data[type+'Days'][d]=data[type+'Days'][d]||{attempts:0,correct:0};}
const missions=[{id:'work',icon:'📚',title:'学校の宿題',text:'宿題を10分やってみる',points:10,page:'homework'},{id:'kuku',icon:'✖️',title:'九九',text:'九九を10問練習する',points:10,page:'kuku'},{id:'math',icon:'➕',title:'筆算',text:'計算問題を3問やってみる',points:10,page:'math'}], moods=[['😄','げんき'],['🙂','まあまあ'],['😐','ふつう'],['😟','しんぱい'],['😴','つかれた']];
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(page).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));scrollTo(0,0)}
function renderMissions(){const d=data.missions[today()]||{};missionList.innerHTML=missions.map(m=>`<article class="mission card ${d[m.id]?'done':''}"><div><div class="mission-icon">${m.icon}</div><h4>${m.title}</h4><p>${m.text}</p></div><div class="stack-buttons"><button class="ghost" data-open="${m.page}">開く</button><button class="${d[m.id]?'ghost':'primary'}" data-mission="${m.id}">${d[m.id]?'できた！ ✓':`やってみた ＋${m.points}pt`}</button></div></article>`).join('')}
function hp(id){return Number(data.homework[id]?.progress||0)} function overall(){const r=homeworkSeed.filter(x=>!x.optional);return Math.round(r.reduce((s,h)=>s+hp(h.id),0)/r.length)}
function hwTarget(id){return id==='challenge'?'kuku':id==='diary'?'home':id==='science'||id==='research'?'explore':id==='tests'||id==='complete'?'math':id==='bookreport'||id==='bookguide'?'report':null}
function renderHomework(){homeworkList.innerHTML=homeworkSeed.map(h=>{const p=hp(h.id),target=hwTarget(h.id);return `<article class="card homework-card"><div><h3>${h.title}${h.optional?' <small class="muted">（希望者）</small>':''}</h3><div class="mini-progress"><span style="width:${p}%"></span></div><small>${p}%</small></div><div class="homework-actions">${target?`<button class="ghost" data-open="${target}">学習する</button>`:''}<button class="ghost" data-hw-minus="${h.id}">−10%</button><button class="primary" data-hw-plus="${h.id}">＋10%</button><button class="ghost" data-hw-done="${h.id}">${p===100?'完了 ✓':'完了'}</button></div></article>`}).join('')}
function renderProgress(){const p=overall();overallPercent.textContent=p+'%';overallBar.style.width=p+'%';progressMessage.textContent=p===100?'学校の宿題、全部達成！すばらしい！':`あと${100-p}%で必須宿題が全部完了です。`}
function renderMood(){const sel=data.daily[today()]?.mood||'';quickMood.innerHTML=moods.map(([e,t])=>`<button class="mood-button ${sel===t?'selected':''}" data-mood="${t}">${e}<small>${t}</small></button>`).join('')}
function renderDiary(){diaryEntries.innerHTML=(data.diaryEntries||[]).slice().reverse().map(x=>`<div class="entry"><strong>${esc(x.date)}</strong><div>${esc(x.note)}</div></div>`).join('')||'<p class="muted">まだ日記はありません。</p>'}
function renderExplore(){exploreEntries.innerHTML=(data.explore||[]).slice().reverse().map(x=>`<article class="card entry"><strong>${esc(x.title)}</strong><small class="muted"> ${esc(x.date)}</small><p>${esc(x.found||'')}</p>${x.photo?`<img src="${x.photo}" alt="観察写真">`:''}</article>`).join('')}
function weakList(obj,n=8){return Object.entries(obj||{}).sort((a,b)=>b[1]-a[1]).slice(0,n)}
function renderStats(){const k=data.kukuDays[today()]||{},m=data.mathDays[today()]||{},completed=homeworkSeed.filter(h=>hp(h.id)===100).length;statsGrid.innerHTML=[['研究ポイント',data.points||0],['称号',badge(data.points||0)],['連続学習',(data.streak.count||0)+'日'],['九九 今日',`${k.correct||0}/${k.attempts||0}`],['計算 今日',`${m.correct||0}/${m.attempts||0}`],['宿題達成率',overall()+'%']].map(([l,v])=>`<div class="stat"><span>${l}</span><strong>${v}</strong></div>`).join('');const kw=weakList(data.kukuWeak).map(([q])=>q),mw=weakList(data.mathWeak).map(([q])=>q);weakSummary.innerHTML=`<p><b>九九：</b>${kw.join('、')||'まだありません'}</p><p><b>計算：</b>${mw.join('、')||'まだありません'}</p>`}
function renderAll(){todayLabel.textContent=new Intl.DateTimeFormat('ja-JP',{dateStyle:'full'}).format(new Date());pointsTotal.textContent=data.points||0;badgeName.textContent=badge(data.points||0);dailyNote.value=data.daily[today()]?.note||'';renderMissions();renderHomework();renderProgress();renderMood();renderDiary();renderExplore();renderStats()}
// 九九
// 小学校で唱える九九の読み方。音声では「かける」「は」を読まず、九九独特の読み方にします。
const kukuHead={
  1:['いんいち','いんに','いんさん','いんし','いんご','いんろく','いんしち','いんはち','いんく'],
  2:['にいち','ににん','にさん','にし','にご','にろく','にしち','にはち','にく'],
  3:['さんいち','さんに','さざん','さんし','さんご','さぶろく','さんしち','さんぱ','さんく'],
  4:['しいち','しに','しさん','しし','しご','しろく','ししち','しは','しく'],
  5:['ごいち','ごに','ごさん','ごし','ごご','ごろく','ごしち','ごは','ごっく'],
  6:['ろくいち','ろくに','ろくさん','ろくし','ろくご','ろくろく','ろくしち','ろくは','ろっく'],
  7:['しちいち','しちに','しちさん','しちし','しちご','しちろく','しちしち','しちは','しちく'],
  8:['はちいち','はちに','はっさん','はちし','はちご','はちろく','はちしち','はっぱ','はっく'],
  9:['くいち','くに','くさん','くし','くご','くろく','くしち','くは','くく']
};
const japaneseNumber=n=>{
  const ones=['','いち','に','さん','し','ご','ろく','しち','はち','く'];
  if(n<10)return ones[n];
  const t=Math.floor(n/10),o=n%10;
  return (t===1?'じゅう':ones[t]+'じゅう')+ones[o];
};
function kukuReading(a,b){const result=a*b;return `${kukuHead[a][b-1]}${result<10?'が':''}${japaneseNumber(result)}`}
function speakJapanese(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.85;window.speechSynthesis.speak(u)}
function tableHTML(d){return `<div class="dan-picker">${[1,2,3,4,5,6,7,8,9].map(x=>`<button data-dan="${x}" class="${x===d?'primary':'ghost'}">${x}の段</button>`).join('')}</div><div class="kuku-table">${[1,2,3,4,5,6,7,8,9].map(x=>`<button class="kuku-line" data-speak="${kukuReading(d,x)}"><b>${d} × ${x}</b><span>${d*x}</span><small>🔊</small></button>`).join('')}</div><button id="finishTable" class="primary full">声に出して練習した ＋5pt</button>`}
function makeKukuQuestions(source='random'){let pool=[];if(source==='weak'&&weakList(data.kukuWeak,30).length)pool=weakList(data.kukuWeak,30).map(([q])=>q.split('×').map(Number));else for(let a=1;a<=9;a++)for(let b=1;b<=9;b++)pool.push([a,b]);kukuQuestions=Array.from({length:10},()=>pool[Math.floor(Math.random()*pool.length)]);kukuArea.innerHTML=`<div class="quiz-list">${kukuQuestions.map(([a,b],i)=>`<label class="quiz-question"><strong>${a} × ${b} ＝</strong><input inputmode="numeric" data-kuku-answer="${i}"></label>`).join('')}</div><button id="checkKuku" class="primary full">10問を答えあわせ</button>`;kukuResult.textContent=''}
function renderKuku(){clearInterval(kukuTimer);if(kukuMode==='table')kukuArea.innerHTML=tableHTML(2);else if(kukuMode==='random')makeKukuQuestions();else if(kukuMode==='weak')makeKukuQuestions('weak');else startTimeAttack()}
function checkKuku(){let correct=0;markStudy('kuku');document.querySelectorAll('[data-kuku-answer]').forEach((x,i)=>{const [a,b]=kukuQuestions[i],q=`${a}×${b}`,ok=Number(x.value)===a*b;x.classList.toggle('ok',ok);x.classList.toggle('bad',!ok);data.kukuDays[today()].attempts++;if(ok){correct++;data.kukuDays[today()].correct++;if(data.kukuWeak[q])data.kukuWeak[q]=Math.max(0,data.kukuWeak[q]-1)}else data.kukuWeak[q]=(data.kukuWeak[q]||0)+1});award(correct);if(correct===10)award(10);save();kukuResult.textContent=`10問中 ${correct}問正解！${correct===10?' 全問正解ボーナス＋10pt！':''}`}
function startTimeAttack(){kukuSeconds=30;kukuScore=0;const next=()=>{const a=1+Math.floor(Math.random()*9),b=1+Math.floor(Math.random()*9);kukuQuestions=[[a,b]];kukuArea.innerHTML=`<div class="timer">残り <b id="timerSec">${kukuSeconds}</b>秒　正解 <b>${kukuScore}</b>問</div><label class="big-question"><strong>${a} × ${b} ＝</strong><input id="timeAnswer" inputmode="numeric" autofocus></label><button id="timeSubmit" class="primary full">答える</button>`;setTimeout(()=>timeAnswer?.focus(),50)};next();kukuTimer=setInterval(()=>{kukuSeconds--;const t=document.getElementById('timerSec');if(t)t.textContent=kukuSeconds;if(kukuSeconds<=0){clearInterval(kukuTimer);award(kukuScore);markStudy('kuku');data.kukuDays[today()].attempts+=kukuScore;data.kukuDays[today()].correct+=kukuScore;save();kukuArea.innerHTML=`<div class="finish-box">30秒で <b>${kukuScore}問</b> 正解！</div><button class="primary full" data-retry-time>もう一度</button>`}},1000)}
// 計算
function makeMath(){let a,b,ans,text,hint,key;if(mathMode==='add'){a=100+Math.floor(Math.random()*800);b=100+Math.floor(Math.random()*800);ans=a+b;text=`${a} ＋ ${b}`;hint='一の位から足します。10をこえたら、十の位へ1を送ろう。'}else if(mathMode==='sub'){a=200+Math.floor(Math.random()*700);b=50+Math.floor(Math.random()*(a-50));ans=a-b;text=`${a} − ${b}`;hint='一の位から引きます。引けない時は左の位から10を借りよう。'}else if(mathMode==='division'){b=2+Math.floor(Math.random()*8);ans=1+Math.floor(Math.random()*9);a=b*ans;text=`${a} ÷ ${b}`;hint=`${b}の段で${a}になる数を探そう。` }else if(mathMode==='word'){const n=2+Math.floor(Math.random()*8),each=2+Math.floor(Math.random()*9);ans=n*each;text=`1箱にあめが${each}こ入っています。${n}箱では何こですか？`;hint=`「1箱に${each}こ」が${n}箱。${each}×${n}で考えよう。`}else {const w=weakList(data.mathWeak,20);if(w.length){key=w[Math.floor(Math.random()*w.length)][0];const parts=key.match(/(\d+) ([＋−÷]) (\d+)/);if(parts){a=+parts[1];b=+parts[3];ans=parts[2]==='＋'?a+b:parts[2]==='−'?a-b:a/b;text=key;hint='前に間違えた問題です。ゆっくり考えよう。'}}if(ans==null){mathMode='add';return makeMath()}}key=text;mathQuestion={ans,text,hint,key};mathArea.innerHTML=`<div class="vertical-wrap">${mathMode==='add'||mathMode==='sub'?verticalHTML(a,b,mathMode==='add'?'+':'−'):`<div class="story-question">${text}</div>`}<label class="answer-box">答え<input id="mathAnswer" inputmode="numeric"></label></div>`;mathResult.textContent='';mathHintText.textContent=''}
function verticalHTML(a,b,op){return `<div class="vertical"><div>${a}</div><div><span>${op}</span>${b}</div><hr><div class="answer-placeholder">?</div></div>`}
function checkMathAnswer(){const v=Number(mathAnswer.value),ok=v===mathQuestion.ans;markStudy('math');data.mathDays[today()].attempts++;if(ok){data.mathDays[today()].correct++;award(5);if(data.mathWeak[mathQuestion.key])data.mathWeak[mathQuestion.key]=Math.max(0,data.mathWeak[mathQuestion.key]-1);mathResult.textContent='正解！＋5ポイント 🎉';mathAnswer.className='ok'}else{data.mathWeak[mathQuestion.key]=(data.mathWeak[mathQuestion.key]||0)+1;mathResult.textContent=`もう一度考えよう。答えは ${mathQuestion.ans}。`;mathAnswer.className='bad'}save()}
// events
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav)go(nav.dataset.page);const open=e.target.closest('[data-open]');if(open)go(open.dataset.open);const m=e.target.closest('[data-mission]');if(m){const d=data.missions[today()]||(data.missions[today()]={});if(!d[m.dataset.mission]){d[m.dataset.mission]=true;award(missions.find(x=>x.id===m.dataset.mission).points);save()}}const plus=e.target.closest('[data-hw-plus]');if(plus){const id=plus.dataset.hwPlus,b=hp(id),a=Math.min(100,b+10);data.homework[id]={progress:a};if(a>b)award(2);save()}const minus=e.target.closest('[data-hw-minus]');if(minus){const id=minus.dataset.hwMinus;data.homework[id]={progress:Math.max(0,hp(id)-10)};save()}const done=e.target.closest('[data-hw-done]');if(done){const id=done.dataset.hwDone,b=hp(id);data.homework[id]={progress:b===100?0:100};if(b<100)award(10);save()}const mood=e.target.closest('[data-mood]');if(mood){data.daily[today()]={...(data.daily[today()]||{}),mood:mood.dataset.mood};save()}const km=e.target.closest('[data-kuku-mode]');if(km){kukuMode=km.dataset.kukuMode;document.querySelectorAll('[data-kuku-mode]').forEach(x=>x.classList.toggle('active',x===km));renderKuku()}const mm=e.target.closest('[data-math-mode]');if(mm){mathMode=mm.dataset.mathMode;document.querySelectorAll('[data-math-mode]').forEach(x=>x.classList.toggle('active',x===mm));makeMath()}const dan=e.target.closest('[data-dan]');if(dan)kukuArea.innerHTML=tableHTML(+dan.dataset.dan);const sp=e.target.closest('[data-speak]');if(sp)speakJapanese(sp.dataset.speak);if(e.target.id==='finishTable'){markStudy('kuku');award(5);save();alert('音読練習できたね！＋5ポイント')}if(e.target.id==='checkKuku')checkKuku();if(e.target.id==='timeSubmit'){const [a,b]=kukuQuestions[0],ok=Number(timeAnswer.value)===a*b,q=`${a}×${b}`;if(ok){kukuScore++;if(data.kukuWeak[q])data.kukuWeak[q]--}else data.kukuWeak[q]=(data.kukuWeak[q]||0)+1;startTimeAttack()}if(e.target.closest('[data-retry-time]'))startTimeAttack()});
resetToday.onclick=()=>{if(confirm('今日の3ミッションだけリセットしますか？')){data.missions[today()]={};save()}};saveDailyNote.onclick=()=>{const note=dailyNote.value.trim();if(!note)return alert('一行日記を書いてください');const old=data.daily[today()]?.note;data.daily[today()]={...(data.daily[today()]||{}),note};if(!old){data.diaryEntries.push({date:today(),note});award(5)}else{const item=data.diaryEntries.find(x=>x.date===today());if(item)item.note=note}save();alert('保存しました')};
const kanjis=[['橋','はし'],['鉄','てつ'],['温','あたたかい'],['調','しらべる'],['究','きわめる']];kanjiList.innerHTML=kanjis.map(([k,r])=>`<div class="kanji-card"><strong>${k}</strong><small>${r}</small></div>`).join('');finishKanji.onclick=()=>{if(data.kanjiDays[today()])return alert('今日はすでにポイントを受け取りました');data.kanjiDays[today()]={memo:kanjiMemo.value.trim()};award(10);save();alert('漢字チャレンジ完了！＋10ポイント')};
newMath.onclick=makeMath;checkMath.onclick=checkMathAnswer;mathHint.onclick=()=>mathHintText.textContent=mathQuestion.hint;
async function fileToDataURL(file){if(!file)return'';if(file.size>2500000)throw new Error('写真は2.5MB以下にしてください');return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}exploreForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{const photo=await fileToDataURL(explorePhoto.files[0]);data.explore.push({title:fd.get('theme'),found:fd.get('found'),date:nowText(),photo});award(8);e.target.reset();save()}catch(err){alert(err.message)}};
exportData.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`miran-lab-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};importData.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data={...clone(defaultData),...JSON.parse(r.result)};save();alert('読み込みました')}catch{alert('読み込めないファイルです')}};r.readAsText(f)};printReport.onclick=()=>print();window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installBtn.classList.add('hidden')}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderKuku();makeMath();renderAll();
