'use strict';
const KEY='miranLabDataV1';
const today=()=>new Date().toISOString().slice(0,10);
const nowText=()=>new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date());
const defaultData={points:0,missions:{},daily:{},explore:[],skate:[],condition:[]};
let data=load(); let currentMood=''; let installPrompt=null;
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function award(n){data.points=Math.max(0,(data.points||0)+n)}
function badge(p){if(p>=150)return'主任研究員';if(p>=80)return'発見マスター';if(p>=40)return'つくば探検家';if(p>=15)return'わくわく研究員';return'はじめの一歩'}
const missions=[
 {id:'study',icon:'✏️',title:'まなび',text:'国語か算数を10分やってみる',points:5},
 {id:'explore',icon:'🔎',title:'探究',text:'「なぜ？」をひとつ見つける',points:5},
 {id:'move',icon:'🛹',title:'からだ',text:'スケボー・散歩・運動を楽しむ',points:5}
];
const moods=[['😄','げんき'],['🙂','まあまあ'],['😐','ふつう'],['😟','しんぱい'],['😴','つかれた']];
function renderMissions(){const day=data.missions[today()]||{};document.querySelector('#missionList').innerHTML=missions.map(m=>`<article class="mission card ${day[m.id]?'done':''}"><div><div class="mission-icon">${m.icon}</div><h4>${m.title}</h4><p>${m.text}</p></div><button class="${day[m.id]?'ghost':'primary'}" data-mission="${m.id}">${day[m.id]?'できた！ ✓':'やってみた'}</button></article>`).join('')}
function renderMoodButtons(sel){return moods.map(([e,t])=>`<button type="button" class="mood-button ${sel===t?'selected':''}" data-mood="${t}" aria-label="${t}">${e}<small>${t}</small></button>`).join('')}
function renderEntries(kind,container){const arr=data[kind]||[];container.innerHTML='';arr.slice().reverse().forEach((entry,revIdx)=>{const idx=arr.length-1-revIdx;const node=document.querySelector('#entryTemplate').content.cloneNode(true);node.querySelector('.entry-title').textContent=entry.title;node.querySelector('time').textContent=entry.date;node.querySelector('.entry-body').innerHTML=entry.html;node.querySelector('.delete-entry').onclick=()=>{if(confirm('この記録を削除しますか？')){data[kind].splice(idx,1);save()}};container.append(node)})}
function renderStats(){const completed=Object.values(data.missions||{}).reduce((n,d)=>n+Object.values(d).filter(Boolean).length,0);document.querySelector('#statsGrid').innerHTML=[['研究ポイント',data.points||0],['完了ミッション',completed],['探究記録',data.explore.length],['スケボー記録',data.skate.length],['体調記録',data.condition.length],['研究員称号',badge(data.points||0)]].map(([l,v])=>`<div class="stat"><span>${l}</span><strong>${v}</strong></div>`).join('')}
function renderAll(){document.querySelector('#todayLabel').textContent=new Intl.DateTimeFormat('ja-JP',{dateStyle:'full'}).format(new Date());document.querySelector('#pointsTotal').textContent=data.points||0;document.querySelector('#badgeName').textContent=badge(data.points||0);renderMissions();document.querySelector('#quickMood').innerHTML=renderMoodButtons(data.daily[today()]?.mood||'');document.querySelector('#conditionMood').innerHTML=renderMoodButtons(currentMood);document.querySelector('#dailyNote').value=data.daily[today()]?.note||'';renderEntries('explore',document.querySelector('#exploreEntries'));renderEntries('skate',document.querySelector('#skateEntries'));renderEntries('condition',document.querySelector('#conditionEntries'));renderStats()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelector('#'+nav.dataset.page).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b===nav));scrollTo(0,0)}const mb=e.target.closest('[data-mission]');if(mb){const d=data.missions[today()]||(data.missions[today()]={});const id=mb.dataset.mission;if(!d[id]){d[id]=true;award(missions.find(m=>m.id===id).points);save()}}const mood=e.target.closest('[data-mood]');if(mood){if(mood.closest('#quickMood')){data.daily[today()]={...(data.daily[today()]||{}),mood:mood.dataset.mood};document.querySelector('#moodMessage').textContent=`今日は「${mood.dataset.mood}」なんだね。教えてくれてありがとう。`;save()}else{currentMood=mood.dataset.mood;renderAll()}}});
document.querySelector('#resetToday').onclick=()=>{const d=data.missions[today()]||{};const count=Object.values(d).filter(Boolean).length;award(-count*5);data.missions[today()]={};save()};
document.querySelector('#saveDailyNote').onclick=()=>{data.daily[today()]={...(data.daily[today()]||{}),note:document.querySelector('#dailyNote').value.trim()};award(1);save();alert('保存しました')};
function makeQuiz(){const level=document.querySelector('#difficulty').value;const max=level==='easy'?10:level==='normal'?30:100;const qs=[];for(let i=0;i<3;i++){let a=1+Math.floor(Math.random()*max),b=1+Math.floor(Math.random()*max),op=Math.random()>.45?'+':'−';if(op==='−'&&b>a)[a,b]=[b,a];qs.push({q:`${a} ${op} ${b} =`,a:op==='+'?a+b:a-b})}window.quizAnswers=qs.map(x=>x.a);document.querySelector('#quizArea').innerHTML=qs.map((x,i)=>`<label class="quiz-question"><strong>${x.q}</strong><input inputmode="numeric" data-answer="${i}" aria-label="問題${i+1}の答え"></label>`).join('');document.querySelector('#quizResult').textContent=''}
document.querySelector('#newQuiz').onclick=makeQuiz;document.querySelector('#difficulty').onchange=makeQuiz;document.querySelector('#checkQuiz').onclick=()=>{let correct=0;document.querySelectorAll('[data-answer]').forEach((el,i)=>{if(Number(el.value)===window.quizAnswers[i])correct++});document.querySelector('#quizResult').textContent=`3問中 ${correct}問正解！ ${correct===3?'すごい！':'取り組んだことが大成功！'}`;if(!document.querySelector('#checkQuiz').dataset.done){award(3+correct);document.querySelector('#checkQuiz').dataset.done='1';save()}};
async function fileToDataURL(file){if(!file)return'';if(file.size>2_500_000)throw new Error('写真が大きすぎます（2.5MB以下にしてください）');return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
document.querySelector('#exploreForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{const photo=await fileToDataURL(document.querySelector('#explorePhoto').files[0]);const theme=fd.get('theme');const parts=[['予想',fd.get('guess')],['やってみた',fd.get('action')],['わかった',fd.get('found')],['次にためす',fd.get('next')]].filter(x=>x[1]).map(x=>`<b>${x[0]}</b>：${esc(x[1])}`).join('\n');data.explore.push({title:theme,date:nowText(),html:`${parts}${photo?`<img src="${photo}" alt="探究写真">`:''}`});award(8);e.target.reset();save()}catch(err){alert(err.message)}};
document.querySelector('#skateForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);data.skate.push({title:fd.get('goal'),date:nowText(),html:`練習 ${esc(fd.get('minutes'))}分／できた回数 ${esc(fd.get('success'))}回\n${esc(fd.get('discovery'))}`});award(6);e.target.reset();save()};
document.querySelector('#energy').oninput=e=>document.querySelector('#energyOutput').textContent=e.target.value;
document.querySelector('#conditionForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);data.condition.push({title:currentMood||'気分未選択',date:nowText(),html:`元気度 ${esc(fd.get('energy'))}/5　睡眠 ${esc(fd.get('sleep')||'—')}時間\n${esc(fd.get('body'))}`});currentMood='';award(2);e.target.reset();document.querySelector('#energyOutput').textContent='3';save()};
document.querySelector('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`miran-lab-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#importData').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result);data={...defaultData,...obj};save();alert('バックアップを読み込みました')}catch{alert('読み込めないファイルです')}};r.readAsText(file)};
document.querySelector('#printReport').onclick=()=>window.print();
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;document.querySelector('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
makeQuiz();renderAll();
